spring:
  application:
    name: DAO_layer
  datasource:
    url: jdbc:postgresql://localhost:5432/my_new_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

sql:
  init:
    mode: always
    schema-locations: classpath:schema.sql

server:
  port: 8080
